"""悬浮窗和主界面的选择按钮。不把游戏、方式写进顶部状态。"""
from __future__ import annotations


def add_panel(dex, ACT, TAP, M, F, Asm, PUB, PRIV, STAT):
    cl = Asm(2, 0)
    cl.const(0, 1)
    cl.sput(0, F(ACT, 'panelOpen', 'I'), 'int')
    cl.ret()
    dex.add_method(ACT, '<clinit>', 'V', (), STAT, cl)

    dp = Asm(6, 2)  # this v4, n v5
    dp.invoke('virtual', M('Landroid/content/Context;', 'getResources', 'Landroid/content/res/Resources;'), [4], 0)
    dp.invoke('virtual', M('Landroid/content/res/Resources;', 'getDisplayMetrics', 'Landroid/util/DisplayMetrics;'), [0], 0)
    dp.iget(1, 0, F('Landroid/util/DisplayMetrics;', 'densityDpi', 'I'))
    dp.mul(1, 5, 1)
    dp.div_lit(1, 1, 160)
    dp.if_gtz(1, 'ok')
    dp.if_lez(5, 'ok')
    dp.const(1, 1)
    dp.label('ok')
    dp.ret(1, 'int')
    dex.add_method(ACT, 'dp', 'I', ('I',), PRIV, dp)

    mk = Asm(6, 3)  # this v3, button v4, on v5
    mk.if_eqz(4, 'out')
    mk.if_eqz(5, 'off')
    mk.const(0, 0xFFF26192)
    mk.const(1, 0xFF2A1020)
    mk.goto('paint')
    mk.label('off')
    mk.const(0, 0xFF1C1C24)
    mk.const(1, 0xFFF4F1F3)
    mk.label('paint')
    mk.new(2, 'Landroid/graphics/drawable/GradientDrawable;')
    mk.invoke('direct', M('Landroid/graphics/drawable/GradientDrawable;', '<init>'), [2])
    mk.invoke('virtual', M('Landroid/graphics/drawable/GradientDrawable;', 'setColor', 'V', ('I',)), [2, 0])
    mk.const(0, 0)
    mk.invoke('virtual', M('Landroid/graphics/drawable/GradientDrawable;', 'setShape', 'V', ('I',)), [2, 0])
    mk.const(0, 0x41400000)  # 12sp-sized corner, 12.0f
    mk.invoke('virtual', M('Landroid/graphics/drawable/GradientDrawable;', 'setCornerRadius', 'V', ('F',)), [2, 0])
    mk.invoke('virtual', M('Landroid/view/View;', 'setBackground', 'V', ('Landroid/graphics/drawable/Drawable;',)), [4, 2])
    mk.invoke('virtual', M('Landroid/widget/TextView;', 'setTextColor', 'V', ('I',)), [4, 1])
    mk.label('out')
    mk.ret()
    dex.add_method(ACT, 'mark', 'V', ('Landroid/widget/Button;', 'I'), PRIV, mk)

    ch = Asm(10, 5)  # this v5, parent v6, text v7, which v8, wide v9
    ch.invoke('virtual', M('Landroid/content/Context;', 'getApplicationContext', 'Landroid/content/Context;', ()), [5], 1)
    ch.new(0, 'Landroid/widget/Button;')
    ch.invoke('direct', M('Landroid/widget/Button;', '<init>', 'V', ('Landroid/content/Context;',)), [0, 1])
    ch.invoke('virtual', M('Landroid/widget/TextView;', 'setText', 'V', ('Ljava/lang/CharSequence;',)), [0, 7])
    ch.const(1, 0)
    ch.invoke('virtual', M('Landroid/widget/TextView;', 'setAllCaps', 'V', ('Z',)), [0, 1])
    ch.const(1, 0x41500000)
    ch.invoke('virtual', M('Landroid/widget/TextView;', 'setTextSize', 'V', ('F',)), [0, 1])
    ch.const(1, 0)
    ch.invoke('direct', M(ACT, 'mark', 'V', ('Landroid/widget/Button;', 'I')), [5, 0, 1])
    ch.const(1, 8)
    ch.invoke('direct', M(ACT, 'dp', 'I', ('I',)), [5, 1], 1, 'int')
    ch.invoke('virtual', M('Landroid/view/View;', 'setPadding', 'V', ('I', 'I', 'I', 'I')), [0, 1, 1, 1, 1])
    ch.new(1, TAP)
    ch.invoke('direct', M(TAP, '<init>', 'V', (ACT, 'I')), [1, 5, 8])
    ch.invoke('virtual', M('Landroid/view/View;', 'setOnClickListener', 'V', ('Landroid/view/View$OnClickListener;',)), [0, 1])
    ch.const(1, -2)
    ch.if_eqz(9, 'wrap')
    ch.const(1, -1)
    ch.label('wrap')
    ch.const(2, 42)
    ch.invoke('direct', M(ACT, 'dp', 'I', ('I',)), [5, 2], 2, 'int')
    ch.new(3, 'Landroid/widget/LinearLayout$LayoutParams;')
    ch.invoke('direct', M('Landroid/widget/LinearLayout$LayoutParams;', '<init>', 'V', ('I', 'I')), [3, 1, 2])
    ch.const(1, 4)
    ch.invoke('direct', M(ACT, 'dp', 'I', ('I',)), [5, 1], 1, 'int')
    ch.iput(1, 3, F('Landroid/view/ViewGroup$MarginLayoutParams;', 'leftMargin', 'I'))
    ch.iput(1, 3, F('Landroid/view/ViewGroup$MarginLayoutParams;', 'topMargin', 'I'))
    ch.iput(1, 3, F('Landroid/view/ViewGroup$MarginLayoutParams;', 'rightMargin', 'I'))
    ch.invoke('virtual', M('Landroid/view/ViewGroup;', 'addView', 'V', ('Landroid/view/View;', 'Landroid/view/ViewGroup$LayoutParams;')), [6, 0, 3])
    ch.ret(0, 'object')
    dex.add_method(ACT, 'choice', 'Landroid/widget/Button;', ('Landroid/view/ViewGroup;', 'Ljava/lang/String;', 'I', 'I'), PRIV, ch)

    cap = Asm(8, 3)  # this v5, parent v6, text v7
    cap.invoke('virtual', M('Landroid/content/Context;', 'getApplicationContext', 'Landroid/content/Context;', ()), [5], 1)
    cap.new(0, 'Landroid/widget/TextView;')
    cap.invoke('direct', M('Landroid/widget/TextView;', '<init>', 'V', ('Landroid/content/Context;',)), [0, 1])
    cap.invoke('virtual', M('Landroid/widget/TextView;', 'setText', 'V', ('Ljava/lang/CharSequence;',)), [0, 7])
    cap.const(1, 0xFF9A93A0)
    cap.invoke('virtual', M('Landroid/widget/TextView;', 'setTextColor', 'V', ('I',)), [0, 1])
    cap.const(1, 0x41400000)
    cap.invoke('virtual', M('Landroid/widget/TextView;', 'setTextSize', 'V', ('F',)), [0, 1])
    cap.const(1, 8)
    cap.invoke('direct', M(ACT, 'dp', 'I', ('I',)), [5, 1], 1, 'int')
    cap.new(2, 'Landroid/widget/LinearLayout$LayoutParams;')
    cap.const(3, -1)
    cap.const(4, -2)
    cap.invoke('direct', M('Landroid/widget/LinearLayout$LayoutParams;', '<init>', 'V', ('I', 'I')), [2, 3, 4])
    cap.iput(1, 2, F('Landroid/view/ViewGroup$MarginLayoutParams;', 'topMargin', 'I'))
    cap.invoke('virtual', M('Landroid/view/ViewGroup;', 'addView', 'V', ('Landroid/view/View;', 'Landroid/view/ViewGroup$LayoutParams;')), [6, 0, 2])
    cap.ret()
    dex.add_method(ACT, 'caption', 'V', ('Landroid/view/ViewGroup;', 'Ljava/lang/String;'), PRIV, cap)

    hr = Asm(8, 2)  # this v6, parent v7
    hr.invoke('virtual', M('Landroid/content/Context;', 'getApplicationContext', 'Landroid/content/Context;', ()), [6], 1)
    hr.new(0, 'Landroid/widget/LinearLayout;')
    hr.invoke('direct', M('Landroid/widget/LinearLayout;', '<init>', 'V', ('Landroid/content/Context;',)), [0, 1])
    hr.const(1, 0)
    hr.invoke('virtual', M('Landroid/widget/LinearLayout;', 'setOrientation', 'V', ('I',)), [0, 1])
    hr.new(1, 'Landroid/widget/LinearLayout$LayoutParams;')
    hr.const(2, -1)
    hr.const(3, -2)
    hr.invoke('direct', M('Landroid/widget/LinearLayout$LayoutParams;', '<init>', 'V', ('I', 'I')), [1, 2, 3])
    hr.invoke('virtual', M('Landroid/view/ViewGroup;', 'addView', 'V', ('Landroid/view/View;', 'Landroid/view/ViewGroup$LayoutParams;')), [7, 0, 1])
    hr.ret(0, 'object')
    dex.add_method(ACT, 'hrow', 'Landroid/widget/LinearLayout;', ('Landroid/view/ViewGroup;',), PRIV, hr)

    pc = Asm(6, 1)  # this v5
    pc.iget(0, 5, F(ACT, 'mode', 'I'))
    pc.const(1, 1)
    pc.if_eq(0, 1, 'mode_in')
    pc.const(2, 1)
    pc.goto('mode_ext')
    pc.label('mode_in')
    pc.const(2, 0)
    pc.label('mode_ext')
    pc.sget(3, F(ACT, 'am0', 'Landroid/widget/Button;'), 'object')
    pc.invoke('direct', M(ACT, 'mark', 'V', ('Landroid/widget/Button;', 'I')), [5, 3, 2])
    pc.sget(3, F(ACT, 'fm0', 'Landroid/widget/Button;'), 'object')
    pc.invoke('direct', M(ACT, 'mark', 'V', ('Landroid/widget/Button;', 'I')), [5, 3, 2])
    pc.const(1, 1)
    pc.if_ne(0, 1, 'mode_out')
    pc.const(2, 1)
    pc.goto('mode_in_set')
    pc.label('mode_out')
    pc.const(2, 0)
    pc.label('mode_in_set')
    pc.sget(3, F(ACT, 'am1', 'Landroid/widget/Button;'), 'object')
    pc.invoke('direct', M(ACT, 'mark', 'V', ('Landroid/widget/Button;', 'I')), [5, 3, 2])
    pc.sget(3, F(ACT, 'fm1', 'Landroid/widget/Button;'), 'object')
    pc.invoke('direct', M(ACT, 'mark', 'V', ('Landroid/widget/Button;', 'I')), [5, 3, 2])
    pc.iget(0, 5, F(ACT, 'game', 'I'))
    for i, field_a, field_f in (
        (0, 'ag0', 'fg0'),
        (1, 'ag1', 'fg1'),
        (2, 'ag2', 'fg2'),
        (3, 'ag3', 'fg3'),
    ):
        pc.const(1, i)
        pc.if_eq(0, 1, f'on{i}')
        pc.const(2, 0)
        pc.goto(f'set{i}')
        pc.label(f'on{i}')
        pc.const(2, 1)
        pc.label(f'set{i}')
        pc.sget(3, F(ACT, field_a, 'Landroid/widget/Button;'), 'object')
        pc.invoke('direct', M(ACT, 'mark', 'V', ('Landroid/widget/Button;', 'I')), [5, 3, 2])
        pc.sget(3, F(ACT, field_f, 'Landroid/widget/Button;'), 'object')
        pc.invoke('direct', M(ACT, 'mark', 'V', ('Landroid/widget/Button;', 'I')), [5, 3, 2])
    pc.ret()
    dex.add_method(ACT, 'paintChoices', 'V', (), PUB, pc)

    def save_choice(name, field, file_name):
        sm = Asm(6, 2)  # this v4, value v5
        sm.if_ltz(5, 'clamp')
        sm.const(0, 4)
        sm.if_lt(5, 0, 'keep')
        sm.label('clamp')
        sm.const(5, 0)
        sm.label('keep')
        sm.iput(5, 4, F(ACT, field, 'I'))
        sm.invoke('static', M('Ljava/lang/Integer;', 'toString', 'Ljava/lang/String;', ('I',)), [5], 1)
        sm.const_string(0, file_name)
        sm.invoke('direct', M(ACT, 'save', 'V', ('Ljava/lang/String;', 'Ljava/lang/String;')), [4, 0, 1])
        sm.invoke('virtual', M(ACT, 'paintChoices', 'V', ()), [4])
        sm.ret()
        dex.add_method(ACT, name, 'V', ('I',), PUB, sm)

    save_choice('setMode', 'mode', 'mode.txt')
    save_choice('setGame', 'game', 'game.txt')

    tg = Asm(6, 1)  # this v5
    tg.sget(0, F(ACT, 'panelOpen', 'I'), 'int')
    tg.if_eqz(0, 'open')
    tg.const(0, 0)
    tg.goto('store')
    tg.label('open')
    tg.const(0, 1)
    tg.label('store')
    tg.sput(0, F(ACT, 'panelOpen', 'I'), 'int')
    tg.sget(1, F(ACT, 'body', 'Landroid/view/View;'), 'object')
    tg.if_eqz(1, 'fold')
    tg.const(2, 0)
    tg.if_nez(0, 'vis')
    tg.const(2, 8)
    tg.label('vis')
    tg.invoke('virtual', M('Landroid/view/View;', 'setVisibility', 'V', ('I',)), [1, 2])
    tg.label('fold')
    tg.sget(1, F(ACT, 'foldBtn', 'Landroid/widget/TextView;'), 'object')
    tg.if_eqz(1, 'fit')
    tg.if_eqz(0, 'say_open')
    tg.const_string(2, '收起')
    tg.goto('say')
    tg.label('say_open')
    tg.const_string(2, '展开')
    tg.label('say')
    tg.invoke('virtual', M('Landroid/widget/TextView;', 'setText', 'V', ('Ljava/lang/CharSequence;',)), [1, 2])
    tg.label('fit')
    tg.invoke('direct', M(ACT, 'fit', 'V', ()), [5])
    tg.ret()
    dex.add_method(ACT, 'togglePanel', 'V', (), PUB, tg)

    ft = Asm(8, 1)  # this v7
    ft.label('s')
    ft.sget(1, F(ACT, 'card', 'Landroid/view/View;'), 'object')
    ft.if_eqz(1, 'out')
    ft.invoke('virtual', M('Landroid/view/View;', 'isAttachedToWindow', 'Z', ()), [1], 0, 'int')
    ft.if_eqz(0, 'out')
    ft.invoke('virtual', M('Landroid/view/View;', 'getLayoutParams', 'Landroid/view/ViewGroup$LayoutParams;'), [1], 2)
    ft.if_eqz(2, 'out')
    ft.const(3, 2)
    ft.new_array(3, 3, '[I')
    ft.invoke('direct', M(ACT, 'sizePanel', 'V', ('[I',)), [7, 3])
    ft.const(4, 0)
    ft.aget(5, 3, 4)
    ft.const(4, 1)
    ft.aget(6, 3, 4)
    ft.iput(5, 2, F('Landroid/view/ViewGroup$LayoutParams;', 'width', 'I'))
    ft.iput(6, 2, F('Landroid/view/ViewGroup$LayoutParams;', 'height', 'I'))
    ft.invoke('virtual', M('Landroid/content/Context;', 'getApplicationContext', 'Landroid/content/Context;', ()), [7], 0)
    ft.const_string(4, 'window')
    ft.invoke('virtual', M('Landroid/content/Context;', 'getSystemService', 'Ljava/lang/Object;', ('Ljava/lang/String;',)), [0, 4], 0)
    ft.check_cast(0, 'Landroid/view/WindowManager;')
    ft.invoke('interface', M('Landroid/view/WindowManager;', 'updateViewLayout', 'V', ('Landroid/view/View;', 'Landroid/view/ViewGroup$LayoutParams;')), [0, 1, 2])
    ft.label('out')
    ft.ret()
    ft.label('h')
    ft.move_exception(0)
    ft.ret()
    ft.try_all('s', 'h', 'h')
    dex.add_method(ACT, 'fit', 'V', (), PRIV, ft)

    sp = Asm(10, 2)  # this v8, out v9
    sp.label('s')
    sp.new(0, 'Landroid/graphics/Point;')
    sp.invoke('direct', M('Landroid/graphics/Point;', '<init>'), [0])
    sp.invoke('virtual', M('Landroid/app/Activity;', 'getWindowManager', 'Landroid/view/WindowManager;'), [8], 1)
    sp.invoke('interface', M('Landroid/view/WindowManager;', 'getDefaultDisplay', 'Landroid/view/Display;'), [1], 1)
    sp.invoke('virtual', M('Landroid/view/Display;', 'getRealSize', 'V', ('Landroid/graphics/Point;',)), [1, 0])
    sp.iget(2, 0, F('Landroid/graphics/Point;', 'x', 'I'))
    sp.iget(3, 0, F('Landroid/graphics/Point;', 'y', 'I'))
    sp.move(4, 2)
    sp.if_lt(2, 3, 'short_ok')
    sp.move(4, 3)
    sp.label('short_ok')
    sp.const(5, 42)
    sp.mul(5, 4, 5)
    sp.div_lit(5, 5, 100)
    sp.const(6, 48)
    sp.mul(6, 2, 6)
    sp.div_lit(6, 6, 100)
    sp.if_lt(5, 6, 'under_cap')
    sp.move(5, 6)
    sp.label('under_cap')
    sp.const(0, 200)
    sp.invoke('direct', M(ACT, 'dp', 'I', ('I',)), [8, 0], 0, 'int')
    sp.if_lt(0, 6, 'floor_ok')
    sp.move(0, 6)
    sp.label('floor_ok')
    sp.if_lt(5, 0, 'use_floor')
    sp.goto('wide_ok')
    sp.label('use_floor')
    sp.move(5, 0)
    sp.label('wide_ok')
    sp.const(0, 16)
    sp.invoke('direct', M(ACT, 'dp', 'I', ('I',)), [8, 0], 0, 'int')
    sp.sub(0, 2, 0)
    sp.if_lt(5, 0, 'on_screen')
    sp.move(5, 0)
    sp.label('on_screen')
    sp.if_gtz(5, 'wide_pos')
    sp.const(5, 240)
    sp.label('wide_pos')
    sp.sget(0, F(ACT, 'panelOpen', 'I'), 'int')
    sp.if_eqz(0, 'collapsed')
    sp.const(6, 56)
    sp.mul(6, 3, 6)
    sp.div_lit(6, 6, 100)
    sp.const(0, 720)
    sp.if_lt(6, 0, 'under_px')
    sp.move(6, 0)
    sp.label('under_px')
    sp.const(0, 70)
    sp.mul(0, 3, 0)
    sp.div_lit(0, 0, 100)
    sp.if_lt(6, 0, 'store')
    sp.move(6, 0)
    sp.goto('store')
    sp.label('collapsed')
    sp.const(0, 96)
    sp.invoke('direct', M(ACT, 'dp', 'I', ('I',)), [8, 0], 6, 'int')
    sp.label('store')
    sp.if_gtz(6, 'tall_pos')
    sp.const(6, 160)
    sp.label('tall_pos')
    sp.const(0, 0)
    sp.aput(5, 9, 0)
    sp.const(0, 1)
    sp.aput(6, 9, 0)
    sp.ret()
    sp.label('h')
    sp.move_exception(0)
    sp.const(0, 0)
    sp.const(1, 320)
    sp.aput(1, 9, 0)
    sp.const(0, 1)
    sp.const(1, 480)
    sp.aput(1, 9, 0)
    sp.ret()
    sp.try_all('s', 'h', 'h')
    dex.add_method(ACT, 'sizePanel', 'V', ('[I',), PRIV, sp)

    bp = Asm(16, 2)  # this v14, text v15
    bp.label('s')
    bp.invoke('virtual', M('Landroid/content/Context;', 'getApplicationContext', 'Landroid/content/Context;', ()), [14], 2)
    bp.new(0, 'Landroid/widget/ScrollView;')
    bp.invoke('direct', M('Landroid/widget/ScrollView;', '<init>', 'V', ('Landroid/content/Context;',)), [0, 2])
    bp.const(3, 1)
    bp.invoke('virtual', M('Landroid/widget/ScrollView;', 'setFillViewport', 'V', ('Z',)), [0, 3])
    bp.new(1, 'Landroid/widget/LinearLayout;')
    bp.invoke('direct', M('Landroid/widget/LinearLayout;', '<init>', 'V', ('Landroid/content/Context;',)), [1, 2])
    bp.const(3, 1)
    bp.invoke('virtual', M('Landroid/widget/LinearLayout;', 'setOrientation', 'V', ('I',)), [1, 3])
    bp.const(3, 14)
    bp.invoke('direct', M(ACT, 'dp', 'I', ('I',)), [14, 3], 3, 'int')
    bp.invoke('virtual', M('Landroid/view/View;', 'setPadding', 'V', ('I', 'I', 'I', 'I')), [1, 3, 3, 3, 3])
    bp.new(4, 'Landroid/graphics/drawable/GradientDrawable;')
    bp.invoke('direct', M('Landroid/graphics/drawable/GradientDrawable;', '<init>'), [4])
    bp.const(5, 0)
    bp.invoke('virtual', M('Landroid/graphics/drawable/GradientDrawable;', 'setShape', 'V', ('I',)), [4, 5])
    bp.const(5, 0xF0121218)
    bp.invoke('virtual', M('Landroid/graphics/drawable/GradientDrawable;', 'setColor', 'V', ('I',)), [4, 5])
    bp.const(5, 0x41A00000)
    bp.invoke('virtual', M('Landroid/graphics/drawable/GradientDrawable;', 'setCornerRadius', 'V', ('F',)), [4, 5])
    bp.invoke('virtual', M('Landroid/view/View;', 'setBackground', 'V', ('Landroid/graphics/drawable/Drawable;',)), [1, 4])
    bp.invoke('direct', M(ACT, 'hrow', 'Landroid/widget/LinearLayout;', ('Landroid/view/ViewGroup;',)), [14, 1], 4)
    bp.new(5, 'Landroid/widget/TextView;')
    bp.invoke('direct', M('Landroid/widget/TextView;', '<init>', 'V', ('Landroid/content/Context;',)), [5, 2])
    bp.const_string(6, 'phisap')
    bp.invoke('virtual', M('Landroid/widget/TextView;', 'setText', 'V', ('Ljava/lang/CharSequence;',)), [5, 6])
    bp.const(6, 0xFFF26192)
    bp.invoke('virtual', M('Landroid/widget/TextView;', 'setTextColor', 'V', ('I',)), [5, 6])
    bp.const(6, 0x41800000)
    bp.invoke('virtual', M('Landroid/widget/TextView;', 'setTextSize', 'V', ('F',)), [5, 6])
    bp.invoke('virtual', M('Landroid/view/ViewGroup;', 'addView', 'V', ('Landroid/view/View;',)), [4, 5])
    bp.sget(5, F(ACT, 'panelOpen', 'I'), 'int')
    bp.if_eqz(5, 'folded')
    bp.const_string(5, '收起')
    bp.goto('fold_make')
    bp.label('folded')
    bp.const_string(5, '展开')
    bp.label('fold_make')
    bp.const(6, 13)
    bp.const(7, 0)
    bp.invoke('direct', M(ACT, 'choice', 'Landroid/widget/Button;', ('Landroid/view/ViewGroup;', 'Ljava/lang/String;', 'I', 'I')), [14, 4, 5, 6, 7], 5)
    bp.sput(5, F(ACT, 'foldBtn', 'Landroid/widget/TextView;'), 'object')
    bp.new(5, 'Landroid/widget/TextView;')
    bp.invoke('direct', M('Landroid/widget/TextView;', '<init>', 'V', ('Landroid/content/Context;',)), [5, 2])
    bp.invoke('virtual', M('Landroid/widget/TextView;', 'setText', 'V', ('Ljava/lang/CharSequence;',)), [5, 15])
    bp.const(6, 0xFFF4F1F3)
    bp.invoke('virtual', M('Landroid/widget/TextView;', 'setTextColor', 'V', ('I',)), [5, 6])
    bp.const(6, 0x41500000)
    bp.invoke('virtual', M('Landroid/widget/TextView;', 'setTextSize', 'V', ('F',)), [5, 6])
    bp.const(6, 4)
    bp.invoke('virtual', M('Landroid/widget/TextView;', 'setMaxLines', 'V', ('I',)), [5, 6])
    bp.sput(5, F(ACT, 'live', 'Landroid/widget/TextView;'), 'object')
    bp.invoke('virtual', M('Landroid/view/ViewGroup;', 'addView', 'V', ('Landroid/view/View;',)), [1, 5])
    bp.new(3, 'Landroid/widget/LinearLayout;')
    bp.invoke('direct', M('Landroid/widget/LinearLayout;', '<init>', 'V', ('Landroid/content/Context;',)), [3, 2])
    bp.const(4, 1)
    bp.invoke('virtual', M('Landroid/widget/LinearLayout;', 'setOrientation', 'V', ('I',)), [3, 4])
    bp.sput(3, F(ACT, 'body', 'Landroid/view/View;'), 'object')
    bp.const_string(4, '计划')
    bp.invoke('direct', M(ACT, 'caption', 'V', ('Landroid/view/ViewGroup;', 'Ljava/lang/String;')), [14, 3, 4])
    bp.new(5, 'Landroid/widget/TextView;')
    bp.invoke('direct', M('Landroid/widget/TextView;', '<init>', 'V', ('Landroid/content/Context;',)), [5, 2])
    bp.const_string(6, '还没有计划')
    bp.invoke('virtual', M('Landroid/widget/TextView;', 'setText', 'V', ('Ljava/lang/CharSequence;',)), [5, 6])
    bp.const(6, 0xFFF4F1F3)
    bp.invoke('virtual', M('Landroid/widget/TextView;', 'setTextColor', 'V', ('I',)), [5, 6])
    bp.const(6, 0x41800000)
    bp.invoke('virtual', M('Landroid/widget/TextView;', 'setTextSize', 'V', ('F',)), [5, 6])
    bp.sput(5, F(ACT, 'fPlan', 'Landroid/widget/TextView;'), 'object')
    bp.invoke('virtual', M('Landroid/view/ViewGroup;', 'addView', 'V', ('Landroid/view/View;',)), [3, 5])
    bp.const_string(4, '偏移')
    bp.invoke('direct', M(ACT, 'caption', 'V', ('Landroid/view/ViewGroup;', 'Ljava/lang/String;')), [14, 3, 4])
    bp.invoke('direct', M(ACT, 'hrow', 'Landroid/widget/LinearLayout;', ('Landroid/view/ViewGroup;',)), [14, 3], 4)
    bp.const_string(5, '−5')
    bp.const(6, 3)
    bp.const(7, 0)
    bp.invoke('direct', M(ACT, 'choice', 'Landroid/widget/Button;', ('Landroid/view/ViewGroup;', 'Ljava/lang/String;', 'I', 'I')), [14, 4, 5, 6, 7])
    bp.new(5, 'Landroid/widget/TextView;')
    bp.invoke('direct', M('Landroid/widget/TextView;', '<init>', 'V', ('Landroid/content/Context;',)), [5, 2])
    bp.const_string(6, '0')
    bp.invoke('virtual', M('Landroid/widget/TextView;', 'setText', 'V', ('Ljava/lang/CharSequence;',)), [5, 6])
    bp.const(6, 0xFFF4F1F3)
    bp.invoke('virtual', M('Landroid/widget/TextView;', 'setTextColor', 'V', ('I',)), [5, 6])
    bp.const(6, 0x41800000)
    bp.invoke('virtual', M('Landroid/widget/TextView;', 'setTextSize', 'V', ('F',)), [5, 6])
    bp.const(6, 16)
    bp.invoke('virtual', M('Landroid/widget/TextView;', 'setGravity', 'V', ('I',)), [5, 6])
    bp.sput(5, F(ACT, 'fOff', 'Landroid/widget/TextView;'), 'object')
    bp.invoke('virtual', M('Landroid/view/ViewGroup;', 'addView', 'V', ('Landroid/view/View;',)), [4, 5])
    bp.const_string(5, '+5')
    bp.const(6, 4)
    bp.const(7, 0)
    bp.invoke('direct', M(ACT, 'choice', 'Landroid/widget/Button;', ('Landroid/view/ViewGroup;', 'Ljava/lang/String;', 'I', 'I')), [14, 4, 5, 6, 7])
    bp.const_string(4, '方式')
    bp.invoke('direct', M(ACT, 'caption', 'V', ('Landroid/view/ViewGroup;', 'Ljava/lang/String;')), [14, 3, 4])
    bp.const_string(5, '外部触摸')
    bp.const(6, 6)
    bp.const(7, 1)
    bp.invoke('direct', M(ACT, 'choice', 'Landroid/widget/Button;', ('Landroid/view/ViewGroup;', 'Ljava/lang/String;', 'I', 'I')), [14, 3, 5, 6, 7], 5)
    bp.sput(5, F(ACT, 'fm0', 'Landroid/widget/Button;'), 'object')
    bp.const_string(5, '进程内')
    bp.const(6, 7)
    bp.const(7, 1)
    bp.invoke('direct', M(ACT, 'choice', 'Landroid/widget/Button;', ('Landroid/view/ViewGroup;', 'Ljava/lang/String;', 'I', 'I')), [14, 3, 5, 6, 7], 5)
    bp.sput(5, F(ACT, 'fm1', 'Landroid/widget/Button;'), 'object')
    bp.const_string(4, '游戏')
    bp.invoke('direct', M(ACT, 'caption', 'V', ('Landroid/view/ViewGroup;', 'Ljava/lang/String;')), [14, 3, 4])
    for text, which, field in (
        ('自动', 9, 'fg0'),
        ('Phigros', 10, 'fg1'),
        ('Phira', 11, 'fg2'),
        ('改版', 12, 'fg3'),
    ):
        bp.const_string(5, text)
        bp.const(6, which)
        bp.const(7, 1)
        bp.invoke('direct', M(ACT, 'choice', 'Landroid/widget/Button;', ('Landroid/view/ViewGroup;', 'Ljava/lang/String;', 'I', 'I')), [14, 3, 5, 6, 7], 5)
        bp.sput(5, F(ACT, field, 'Landroid/widget/Button;'), 'object')
    bp.const_string(5, '停止')
    bp.const(6, 2)
    bp.const(7, 1)
    bp.invoke('direct', M(ACT, 'choice', 'Landroid/widget/Button;', ('Landroid/view/ViewGroup;', 'Ljava/lang/String;', 'I', 'I')), [14, 3, 5, 6, 7], 5)
    bp.const(6, 1)
    bp.invoke('direct', M(ACT, 'mark', 'V', ('Landroid/widget/Button;', 'I')), [14, 5, 6])
    bp.sget(4, F(ACT, 'panelOpen', 'I'), 'int')
    bp.if_nez(4, 'body_on')
    bp.const(4, 8)
    bp.invoke('virtual', M('Landroid/view/View;', 'setVisibility', 'V', ('I',)), [3, 4])
    bp.label('body_on')
    bp.invoke('virtual', M('Landroid/view/ViewGroup;', 'addView', 'V', ('Landroid/view/View;',)), [1, 3])
    bp.new(4, 'Landroid/widget/LinearLayout$LayoutParams;')
    bp.const(5, -1)
    bp.const(6, -2)
    bp.invoke('direct', M('Landroid/widget/LinearLayout$LayoutParams;', '<init>', 'V', ('I', 'I')), [4, 5, 6])
    bp.invoke('virtual', M('Landroid/view/ViewGroup;', 'addView', 'V', ('Landroid/view/View;', 'Landroid/view/ViewGroup$LayoutParams;')), [0, 1, 4])
    bp.invoke('virtual', M(ACT, 'paintChoices', 'V', ()), [14])
    bp.ret(0, 'object')
    bp.label('h')
    bp.move_exception(0)
    bp.const(0, 0)
    bp.ret(0, 'object')
    bp.try_all('s', 'h', 'h')
    dex.add_method(ACT, 'buildPanel', 'Landroid/view/View;', ('Ljava/lang/String;',), PRIV, bp)

    am = Asm(12, 1)  # this v11
    am.label('s')
    am.iget(1, 11, F(ACT, 'statusView', 'Landroid/widget/TextView;'), 'object')
    am.if_eqz(1, 'out')
    am.invoke('virtual', M('Landroid/view/View;', 'getParent', 'Landroid/view/ViewParent;'), [1], 2)
    am.if_eqz(2, 'out')
    am.check_cast(2, 'Landroid/view/ViewGroup;')
    am.invoke('virtual', M('Landroid/view/ViewGroup;', 'indexOfChild', 'I', ('Landroid/view/View;',)), [2, 1], 3, 'int')
    am.add_lit(3, 3, 1)
    am.new(0, 'Landroid/widget/LinearLayout;')
    am.invoke('direct', M('Landroid/widget/LinearLayout;', '<init>', 'V', ('Landroid/content/Context;',)), [0, 11])
    am.const(4, 1)
    am.invoke('virtual', M('Landroid/widget/LinearLayout;', 'setOrientation', 'V', ('I',)), [0, 4])
    am.const(4, 12)
    am.invoke('direct', M(ACT, 'dp', 'I', ('I',)), [11, 4], 4, 'int')
    am.invoke('virtual', M('Landroid/view/View;', 'setPadding', 'V', ('I', 'I', 'I', 'I')), [0, 4, 4, 4, 4])
    am.const(4, 0xFF1C1C24)
    am.invoke('virtual', M('Landroid/view/View;', 'setBackgroundColor', 'V', ('I',)), [0, 4])
    am.new(5, 'Landroid/widget/LinearLayout$LayoutParams;')
    am.const(6, -1)
    am.const(7, -2)
    am.invoke('direct', M('Landroid/widget/LinearLayout$LayoutParams;', '<init>', 'V', ('I', 'I')), [5, 6, 7])
    am.const(6, 12)
    am.invoke('direct', M(ACT, 'dp', 'I', ('I',)), [11, 6], 6, 'int')
    am.iput(6, 5, F('Landroid/view/ViewGroup$MarginLayoutParams;', 'topMargin', 'I'))
    am.invoke('virtual', M('Landroid/view/View;', 'setLayoutParams', 'V', ('Landroid/view/ViewGroup$LayoutParams;',)), [0, 5])
    am.invoke('virtual', M('Landroid/view/ViewGroup;', 'addView', 'V', ('Landroid/view/View;', 'I')), [2, 0, 3])
    am.const_string(4, '方式')
    am.invoke('direct', M(ACT, 'caption', 'V', ('Landroid/view/ViewGroup;', 'Ljava/lang/String;')), [11, 0, 4])
    am.invoke('direct', M(ACT, 'hrow', 'Landroid/widget/LinearLayout;', ('Landroid/view/ViewGroup;',)), [11, 0], 8)
    am.const_string(4, '外部触摸')
    am.const(5, 6)
    am.const(6, 0)
    am.invoke('direct', M(ACT, 'choice', 'Landroid/widget/Button;', ('Landroid/view/ViewGroup;', 'Ljava/lang/String;', 'I', 'I')), [11, 8, 4, 5, 6], 9)
    am.sput(9, F(ACT, 'am0', 'Landroid/widget/Button;'), 'object')
    am.const_string(4, '进程内')
    am.const(5, 7)
    am.const(6, 0)
    am.invoke('direct', M(ACT, 'choice', 'Landroid/widget/Button;', ('Landroid/view/ViewGroup;', 'Ljava/lang/String;', 'I', 'I')), [11, 8, 4, 5, 6], 9)
    am.sput(9, F(ACT, 'am1', 'Landroid/widget/Button;'), 'object')
    am.const_string(4, '游戏')
    am.invoke('direct', M(ACT, 'caption', 'V', ('Landroid/view/ViewGroup;', 'Ljava/lang/String;')), [11, 0, 4])
    am.invoke('direct', M(ACT, 'hrow', 'Landroid/widget/LinearLayout;', ('Landroid/view/ViewGroup;',)), [11, 0], 8)
    am.const_string(4, '自动')
    am.const(5, 9)
    am.const(6, 0)
    am.invoke('direct', M(ACT, 'choice', 'Landroid/widget/Button;', ('Landroid/view/ViewGroup;', 'Ljava/lang/String;', 'I', 'I')), [11, 8, 4, 5, 6], 9)
    am.sput(9, F(ACT, 'ag0', 'Landroid/widget/Button;'), 'object')
    am.const_string(4, 'Phigros')
    am.const(5, 10)
    am.const(6, 0)
    am.invoke('direct', M(ACT, 'choice', 'Landroid/widget/Button;', ('Landroid/view/ViewGroup;', 'Ljava/lang/String;', 'I', 'I')), [11, 8, 4, 5, 6], 9)
    am.sput(9, F(ACT, 'ag1', 'Landroid/widget/Button;'), 'object')
    am.invoke('direct', M(ACT, 'hrow', 'Landroid/widget/LinearLayout;', ('Landroid/view/ViewGroup;',)), [11, 0], 8)
    am.const_string(4, 'Phira')
    am.const(5, 11)
    am.const(6, 0)
    am.invoke('direct', M(ACT, 'choice', 'Landroid/widget/Button;', ('Landroid/view/ViewGroup;', 'Ljava/lang/String;', 'I', 'I')), [11, 8, 4, 5, 6], 9)
    am.sput(9, F(ACT, 'ag2', 'Landroid/widget/Button;'), 'object')
    am.const_string(4, '改版')
    am.const(5, 12)
    am.const(6, 0)
    am.invoke('direct', M(ACT, 'choice', 'Landroid/widget/Button;', ('Landroid/view/ViewGroup;', 'Ljava/lang/String;', 'I', 'I')), [11, 8, 4, 5, 6], 9)
    am.sput(9, F(ACT, 'ag3', 'Landroid/widget/Button;'), 'object')
    am.invoke('virtual', M(ACT, 'paintChoices', 'V', ()), [11])
    am.label('out')
    am.ret()
    am.label('h')
    am.move_exception(0)
    am.ret()
    am.try_all('s', 'h', 'h')
    dex.add_method(ACT, 'addModes', 'V', (), PRIV, am)
