plugins {
    id "com.android.application"
}

android {
    namespace "app.phisap.pocket"
    compileSdk 34

    defaultConfig {
        applicationId "app.phisap.pocket"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "0.1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.7.0"
    compileOnly project(":xposed-stub")
}
